INSERT INTO DATE_INTERVAL
VALUES(1234, '2001-02-11','Winter', '00:00:00');
SELECT * FROM DATE_INTERVAL;
INSERT INTO BUILDING
VALUES(1234, 'IKE', 'Never', 5);
INSERT INTO BUILDING_TYPE
VALUES('Bedroom', 'Cool');
INSERT INTO BUILDING_TYPE
VALUES('IKE', 'Cool'); 
INSERT INTO ENERGY_SOURCE
VALUES(1234, 'YEET', 'Fuel Oil');
INSERT INTO FUEL_OIL
VALUES (1234, 'kbtu', 'fuel oil'); 
INSERT INTO NATURAL_GAS
VALUES (1234, 'kbtu', 'fuel oil'); 
INSERT INTO ELECTRIC_GRID
VALUES (1234, 'kbtu', 'fuel oil'); 
INSERT INTO OTHER_SOURCE
VALUES (1234, 'kbtu', 'fuel oil'); 
INSERT INTO ENERGY_SOURCE_COST
VALUES(1234, 0.62, 989);
UPDATE DATE_INTERVAL
SET StartDate = ‘09-10-2001’, End Date = ‘10-10-2001’
WHERE MeterConsumptionID = 1234;
UPDATE DATE_INTERVAL
SET StartDate = '2001-09-10'
WHERE meter_consumption_id = '1234';
UPDATE BUILDING
SET Name = 'I like IKE'
WHERE  Name = 'IKE';
SELECT * FROM BUILDING;
INSERT INTO BUILDING
VALUES(12345, 'I like IKE', 'Never', 6);
UPDATE BUILDING_TYPE
SET Name = 'I like IKE'
WHERE  name = 'IKE';
select * from building_type;
select * from building;
select * from building_type;
UPDATE BUILDING_TYPE
SET Property_Type = ‘Dormitory’
WHERE Property_Type = ‘ResidenceHall/Dormitory’;
UPDATE BUILDING_TYPE
SET Property_Type = 'Cooler'
WHERE Property_Type = 'Cool';
UPDATE FUEL_OIL
SET Units = ‘gallons’
WHERE Units = ‘kbtu’;
UPDATE FUEL_OIL
SET Units = 'gallons'
WHERE Units = 'kbtu';
UPDATE NATURAL_GAS
SET Units = 'gallons'
WHERE Units = 'kbtu';
UPDATE ELECTRIC_GRID
SET Units = 'gallons'
WHERE Units = 'kbtu';
UPDATE OTHER_SOURCE
SET Units = 'gallons'
WHERE Units = 'kbtu';
SELECT * OTHER_SOURCE;
SELECT* FROM OTHER_SOURCE;
SELECT * FROM ENERGY_SOURCE;
SELECT * FROM ENERGY_SOURCE_COST;
UPDATE ENERGY_SOURCE_COST
SET Cost = 0
WHERE Usage_Amount = 989;
SELECT * FROM ENERGY_SOURCE;
SELECT * FROM DATE_INTERVAL;
DELETE FROM DATE_INTERVAL
WHERE Meter_Consumption_ID = '1234';
SELECT * FROM DATE_INTERVAL;
DELETE FROM BUILDING
WHERE nAME ='IKE';
SELECT * FROM BUILDING;
DELETE FROM BUILDING
WHERE nAME ='I like IKE';
DELETE FROM BUILDING_TYPE
WHERE nAME ='I like IKE';
DELETE FROM NATURAL_GAS
WHERE PortfolioManagerMeterID = 1234;
DELETE FROM NATURAL_GAS
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM fuel_oil
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM electric_grid
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM other_source
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM energy_source
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM energy_source_cost
WHERE Portfolio_Manager_Meter_ID = 1234;
DELETE FROM energy_source
WHERE Portfolio_Manager_Meter_ID = 1234;
SELECT * FROM yEAR_ENERGY_SOURCE_KBTU_COST;
SELECT * FROM month_ENERGY_SOURCE_KBTU_COST;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
CREATE OR REPLACE VIEW MINUTE_ENERGY_SOURCE_KBTU_COST AS
SELECT StartTimestamp, Cost, Usage_Amount, Usage_Amount/(cast(Cost as float) * 30 * 24 * 4) AS kbtuPerCost
FROM DATE_INTERVAL NATURAL JOIN MAPS_TO NATURAL JOIN ENERGY_SOURCE_COST NATURAL JOIN ENERGY_SOURCE
GROUP BY StartDate, StartTimestamp, Usage_Amount, Cost;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
DROP VIEW MINUTE_ENERGY_SOURCE_KBTU_COST;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
DROP VIEW MINUTE_ENERGY_SOURCE_KBTU_COST;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
DROP VIEW MINUTE_ENERGY_SOURCE_KBTU_COST;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
DROP VIEW MINUTE_ENERGY_SOURCE_KBTU_COST;
CREATE VIEW MINUTE_ENERGY_SOURCE_KBTU_COST AS
SELECT StartDate, StartTimestamp, cast(Cost as float)/(30 * 24 * 4) AS cost, Usage_Amount, Usage_Amount/(cast(Cost as float) * 30 * 24 * 4) AS kbtuPerCost
FROM DATE_INTERVAL NATURAL JOIN MAPS_TO NATURAL JOIN ENERGY_SOURCE_COST NATURAL JOIN ENERGY_SOURCE
GROUP BY StartDate, StartTimestamp, Usage_Amount, Cost
ORDER BY StartDate ASC;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
DROP VIEW MINUTE_ENERGY_SOURCE_KBTU_COST;
CREATE VIEW MINUTE_ENERGY_SOURCE_KBTU_COST AS
SELECT StartDate, StartTimestamp, cast(Cost as float)/(30 * 24 * 4) AS cost, cast(Usage_Amount as float)/ (30*24*4) AS Usage_Amt, Usage_Amount/(cast(Cost as float) * 30 * 24 * 4) AS kbtuPerCost
FROM DATE_INTERVAL NATURAL JOIN MAPS_TO NATURAL JOIN ENERGY_SOURCE_COST NATURAL JOIN ENERGY_SOURCE
GROUP BY StartDate, StartTimestamp, Usage_Amount, Cost
ORDER BY StartDate ASC;
SELECT * FROM minute_ENERGY_SOURCE_KBTU_COST;
